### PR TITLE
Fix sponsor page for mobile view

### LINKED ISSUE #534: Sponsor tier layout
- On mobile (1080 x 2400) and laptop full HD, the ribbons are overshadowing "available" in the last four packages. 
image

- Platinum "X" is overlapping with the ribbon
image

### PR DESCRIPTION
**Pull request by egeakman**
- Fix the ribbon covering the text (a better looking solution would be nice instead of this fix)
- Fix buttons sticking too close

image -> image

image -> image

closes #534

### CODE REVIEW

**Comment by hypha** [comment]
closes https://github.com/EuroPython/website/issues/534

File: src/components/sponsor-tiers/sponsor-tiers.tsx [hunk 1]
```diff
@@ -72,7 +72,10 @@ const SponsorTier = ({
       : price;
 
   return (
-    <div className="bg-white text-black rounded-2xl p-6 relative not-prose">
+    <div
+      className="bg-white text-black rounded-2xl p-6 relative not-prose"
+      style={{ zIndex: 0 }}
```
Comment (patrick91) [inline src/components/sponsor-tiers/sponsor-tiers.tsx:77]: I think you can do `z-0` with tailwind, but what does it do in this case?

File: src/content/pages/sponsor.mdx [hunk 2]
```diff
@@ -41,7 +41,7 @@ accessible to most organisations keen to help the community.
 <div style={{textAlign: "left", marginBottom: "30px"}}>
```
Comment (patrick91) [inline src/content/pages/sponsor.mdx:41]: could be nicer to use tailwind's space-y class here, instead of using a class on the button: https://tailwindcss.com/docs/space

what do you think? 😊

**Review by patrick91 — CHANGES_REQUESTED** [review]
left some comments! the output looks great, but I think we can improve the code a bit 😊

File: src/components/sponsor-tiers/sponsor-tiers.tsx (hunk 1 above)
Comment (egeakman) [reply src/components/sponsor-tiers/sponsor-tiers.tsx:77]: Yep, z-0 is nicer. Without setting the z-index, the ribbon is sent all the way back:
image

And if the ribbon's z-index is anything other than ``-1``, it stays on top of the text.

**Review by patrick91 — APPROVED** [review]
